# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Guide
  items:
    - label: 'Creating docs'
      link: '/guide/creating-docs'
    - label: 'Member'
      link: '/guide/member'
    - label: 'Templates'
      link: '/guide/templates'
- label: GrowthHack
  items:
    - label: 'ALL'
      link: '/tips/growthhack/all'
    - label: 'Twitter'
      link: '/tips/growthhack/twitter'
- label: IaC
  items:
    - label: 'ALL'
      link: '/tips/IaC/cdk/all'
    - label: 'CDK-ECS-Fargate-FastAPI'
      link: '/tips/IaC/cdk/fargate-fastAPI'
    - label: 'CDK-SAM'
      link: '/tips/IaC/cdk/sam'
    - label: 'CDK-Lambda-APIGateway'
      link: '/tips/IaC/cdk/lambda-apigateway'